### ISSUE TITLE
travis-ci build timeout

### ISSUE THREAD

**Issue by FreddieChopin** [ucgosupl/mm_legend_v2#3]
Hi!

To (mostly) solve (most of) the issues with building bleeding-edge-toolchain in travis-ci, please add this environment variable to the toolchain build step:

    XZ_OPT="-0 -T 0 -v"

Example:

https://github.com/DISTORTEC/distortos/blob/master/.travis.yml#L41

This way very low compression will be used for toolchain - the package will use more space, but the compression itself is at least 10x faster than with default settings used in script (extreme compression level).

Another thing that may help you is caching - I've implemented that in my scripts too. Generally there's no point in building the toolchain with each job, you can safely build it once and only rebuild it when necessary (new version, changes to the scripts, ...). If you set travis to repeat the build at least every week, there's a high change that the cache won't be purged, so the toolchain will always be available.

Generally the 50 minute timeout is the biggest issue on travis which sometimes still gives trouble - you just have to repeat the job until it finally works /;

**Comment by ucgosupl** [comment]
Thanks for your advice and also for all resources that you publish online! You are doing great work. I adapted a lot of your code for my needs and it solved many of my problems. 

After adding these xz options build finishes before time limit. Altough I must use Precise distro - on Trusty it takes longer and I never fit into time limit. Travis ends support for docker based builds on Ubuntu Precise so it might be issue in the future.

I use caching too so after first build ends successfully, next builds takes about 2 minutes.

**Comment by FreddieChopin** [comment]
Yes, on "trusty" the build often takes a bit longer, which is just enough for the whole thing to exceed the limit /; However sometimes it works "fast enough", that's why I usually end up restarting the build several times until it works (; In the (near) future I'll have to come up with a better solution, as this is becoming really tedious...

As for the caching, I noticed that whatever you do the cache gets purged once a month anyway /; Sometimes even more often.

**Comment by ucgosupl** [comment]
For now using precompiled binary

**Comment by FreddieChopin** [comment]
There are GCC 6 and GCC 7 precompiled toolchains built specifically for travis-CI used by my distortos project. If you want, you may use them, but these are not "official" and there will be only the most recent versions available due to server storage limits.

https://github.com/DISTORTEC/distortos/blob/master/scripts/travis-ci.sh

**Comment by ucgosupl** [comment]
Thanks. I will stay with public gcc5 binary from your site for now. It is enough for my needs and I won't need to update it that often.
